version: "3"
services:
  mysql_container:
    image: mysql
    ports:
      - 8080:8080
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - type: volume
        source: sql-data
        target: /var/lib/mysql

  nodejs_container:
    image: my_custom_node_image
    ports:
      - 3000:3000
volumes:
  sql-data:
    driver: local
