version: "3"
services:
  mysql_container:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - type: volume
        source: sql-data
        target: /var/lib/mysql

  nodejs_container:
    image: new_app
    ports:
      - 8080:8080
volumes:
  sql-data:
    driver: local
